# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1257, 842)
        self.MainWindowFrame = QtWidgets.QWidget(MainWindow)
        self.MainWindowFrame.setAutoFillBackground(False)
        self.MainWindowFrame.setObjectName("MainWindowFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MainWindowFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SelectedData = QtWidgets.QTabWidget(self.MainWindowFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelectedData.sizePolicy().hasHeightForWidth())
        self.SelectedData.setSizePolicy(sizePolicy)
        self.SelectedData.setMinimumSize(QtCore.QSize(300, 0))
        self.SelectedData.setObjectName("SelectedData")
        self.SelectedDataFrame = QtWidgets.QWidget()
        self.SelectedDataFrame.setObjectName("SelectedDataFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SelectedDataFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SelectedDataTable = QtWidgets.QTableView(self.SelectedDataFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelectedDataTable.sizePolicy().hasHeightForWidth())
        self.SelectedDataTable.setSizePolicy(sizePolicy)
        self.SelectedDataTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SelectedDataTable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SelectedDataTable.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SelectedDataTable.setLineWidth(0)
        self.SelectedDataTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.SelectedDataTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.SelectedDataTable.setAlternatingRowColors(True)
        self.SelectedDataTable.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.SelectedDataTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.SelectedDataTable.setObjectName("SelectedDataTable")
        self.SelectedDataTable.horizontalHeader().setCascadingSectionResizes(False)
        self.SelectedDataTable.horizontalHeader().setDefaultSectionSize(100)
        self.SelectedDataTable.horizontalHeader().setMinimumSectionSize(1)
        self.SelectedDataTable.horizontalHeader().setSortIndicatorShown(False)
        self.SelectedDataTable.horizontalHeader().setStretchLastSection(True)
        self.SelectedDataTable.verticalHeader().setVisible(False)
        self.SelectedDataTable.verticalHeader().setHighlightSections(False)
        self.SelectedDataTable.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_3.addWidget(self.SelectedDataTable)
        self.SelectedData.addTab(self.SelectedDataFrame, "")
        self.horizontalLayout.addWidget(self.SelectedData)
        self.GuiTabs = QtWidgets.QTabWidget(self.MainWindowFrame)
        self.GuiTabs.setObjectName("GuiTabs")
        self.FilterData = QtWidgets.QWidget()
        self.FilterData.setObjectName("FilterData")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.FilterData)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.FilterGroup1 = QtWidgets.QGroupBox(self.FilterData)
        self.FilterGroup1.setObjectName("FilterGroup1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.FilterGroup1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FilterAddButton = QtWidgets.QPushButton(self.FilterGroup1)
        self.FilterAddButton.setObjectName("FilterAddButton")
        self.horizontalLayout_2.addWidget(self.FilterAddButton)
        self.FilterRemButton = QtWidgets.QPushButton(self.FilterGroup1)
        self.FilterRemButton.setObjectName("FilterRemButton")
        self.horizontalLayout_2.addWidget(self.FilterRemButton)
        self.verticalLayout.addWidget(self.FilterGroup1)
        self.FilterGroup2 = QtWidgets.QGroupBox(self.FilterData)
        self.FilterGroup2.setObjectName("FilterGroup2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.FilterGroup2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.FilterRad1 = QtWidgets.QRadioButton(self.FilterGroup2)
        self.FilterRad1.setObjectName("FilterRad1")
        self.verticalLayout_4.addWidget(self.FilterRad1)
        self.verticalLayout.addWidget(self.FilterGroup2)
        self.FiltertableView = QtWidgets.QTableView(self.FilterData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FiltertableView.sizePolicy().hasHeightForWidth())
        self.FiltertableView.setSizePolicy(sizePolicy)
        self.FiltertableView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.FiltertableView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FiltertableView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FiltertableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.FiltertableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.FiltertableView.setAlternatingRowColors(True)
        self.FiltertableView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.FiltertableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.FiltertableView.setSortingEnabled(True)
        self.FiltertableView.setObjectName("FiltertableView")
        self.FiltertableView.horizontalHeader().setCascadingSectionResizes(False)
        self.FiltertableView.horizontalHeader().setSortIndicatorShown(True)
        self.FiltertableView.horizontalHeader().setStretchLastSection(True)
        self.FiltertableView.verticalHeader().setVisible(False)
        self.FiltertableView.verticalHeader().setHighlightSections(False)
        self.FiltertableView.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.FiltertableView)
        self.GuiTabs.addTab(self.FilterData, "")
        self.PlotSpectra = QtWidgets.QWidget()
        self.PlotSpectra.setObjectName("PlotSpectra")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.PlotSpectra)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PlotButton = QtWidgets.QPushButton(self.PlotSpectra)
        self.PlotButton.setObjectName("PlotButton")
        self.verticalLayout_2.addWidget(self.PlotButton)
        self.matplotlib = QtWidgets.QWidget(self.PlotSpectra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlib.sizePolicy().hasHeightForWidth())
        self.matplotlib.setSizePolicy(sizePolicy)
        self.matplotlib.setAutoFillBackground(False)
        self.matplotlib.setObjectName("matplotlib")
        self.mpl_layout = QtWidgets.QVBoxLayout(self.matplotlib)
        self.mpl_layout.setContentsMargins(0, 0, 0, 0)
        self.mpl_layout.setObjectName("mpl_layout")
        self.verticalLayout_2.addWidget(self.matplotlib)
        self.GuiTabs.addTab(self.PlotSpectra, "")
        self.horizontalLayout.addWidget(self.GuiTabs)
        MainWindow.setCentralWidget(self.MainWindowFrame)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1257, 29))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_Data = QtWidgets.QAction(MainWindow)
        self.actionLoad_Data.setObjectName("actionLoad_Data")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuFile.addAction(self.actionExit_2)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.SelectedData.setCurrentIndex(0)
        self.GuiTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SelectedData.setTabText(self.SelectedData.indexOf(self.SelectedDataFrame), _translate("MainWindow", "Selected Data"))
        self.FilterGroup1.setTitle(_translate("MainWindow", "  Add/remove highlighted choices to/from the sidebar"))
        self.FilterAddButton.setText(_translate("MainWindow", "Add..."))
        self.FilterRemButton.setText(_translate("MainWindow", "Remove..."))
        self.FilterGroup2.setTitle(_translate("MainWindow", "  Filter by..."))
        self.FilterRad1.setText(_translate("MainWindow", "RadioB&utton"))
        self.GuiTabs.setTabText(self.GuiTabs.indexOf(self.FilterData), _translate("MainWindow", "Filter Data"))
        self.PlotButton.setText(_translate("MainWindow", "Plot"))
        self.GuiTabs.setTabText(self.GuiTabs.indexOf(self.PlotSpectra), _translate("MainWindow", "View Spectra"))
        self.menuFile.setTitle(_translate("MainWindow", "F&ile"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionLoad_Data.setText(_translate("MainWindow", "&Load Data"))
        self.actionExit_2.setText(_translate("MainWindow", "&Exit"))

